brew "stow"
brew "zsh"
brew "git"
brew "rbenv"
brew "coreutils"

tap "homebrew/cask"
cask "iterm2"
cask "Spectacle"
cask "Spotify"
cask "google-chrome"
cask "Grammarly"
cask "Firefox"
cask "1Password"
cask "Docker"
cask "Postman"
cask "visual-studio-code"
cask "clipy"
