brew "stow"
brew "zsh"
brew "git"
brew "rbenv"
brew "coreutils"

tap "homebrew/cask"
cask "Spectacle"
cask "Telegram"
cask "Sublime Text"
cask "Firefox"
cask "1Password"
cask "Docker"
cask "Postman"
cask "Altair"
cask "Visual Studio Code"
