#!/bin/bash

# Install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


# Install packages with Brewfile
brew update
brew bundle

stow=`which stow`
stow_root=`dirname $0`
stow_packages=`find ${stow_root} -type d -depth 1 -not -name ".*" -exec basename {} \;`

for package in ${stow_packages}; do
  echo "Installing ${package}"
  ${stow} ${package}
done

# Install sublime settings
`~/dotfiles/sublime/install.sh`

# Use zsh as default shell
chsh -s /bin/zsh 
