#!/bin/bash

# Install packages with Brewfile
brew update
brew bundle

stow=`which stow`
stow_root=`dirname $0`
stow_packages=`find ${stow_root} -type d -depth 1 -not -name ".*" -exec basename {} \;`

for package in ${stow_packages}; do
  echo "Installing ${package}"
  ${stow} ${package}
done

# Install sublime settings
`~/dotfiles/sublime/install.sh`

# Use zsh as default shell
sudo -s chsh -s /bin/zsh
