#!/bin/bash

stow=`which stow`
stow_root=`dirname $0`
stow_packages=`find ${stow_root} -type d -depth 1 -not -name ".*" -exec basename {} \;`

for package in ${stow_packages}; do
  echo "Installing ${package}"
  ${stow} ${package}
done
